# Generated by Django 5.0.1 on 2024-07-29 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_profile_avatar_alter_profile_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="admin",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="profile",
            name="theme",
            field=models.CharField(blank=True, default="light", max_length=10),
        ),
    ]
