# Generated by Django 5.0.1 on 2024-07-31 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_profile_currency"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="country_purchased",
            new_name="country",
        ),
        migrations.AddField(
            model_name="profile",
            name="display_name",
            field=models.TextField(blank=True, null=True),
        ),
    ]
