# Generated by Django 5.0.1 on 2024-11-24 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_rename_country_purchased_profile_country_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="theme",
            field=models.CharField(blank=True, default="dark", max_length=10),
        ),
    ]
