# Generated by Django 5.0.1 on 2024-11-24 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_profile_theme"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="theme",
        ),
    ]
