# Generated by Django 5.0.1 on 2024-07-28 15:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drink", "0004_alter_drink_approved_by_alter_drink_drink_brand_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="images",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.ImageField(default="default.png", upload_to="drinks"),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
    ]
