# Generated by Django 5.0.1 on 2024-07-28 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drink", "0005_alter_review_images"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="images",
        ),
        migrations.AddField(
            model_name="review",
            name="image",
            field=models.ImageField(default="default.png", upload_to="drinks"),
        ),
    ]
