# Generated by Django 5.0.1 on 2024-07-29 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drink", "0007_remove_drink_images_drink_image_alter_review_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="aftertaste",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="review",
            name="taste",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="drink",
            name="approved",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="drinkbrand",
            name="approved",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
