# Generated by Django 5.0.1 on 2024-07-29 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drink", "0008_review_aftertaste_review_taste_alter_drink_approved_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="city_purchased",
        ),
        migrations.AddField(
            model_name="drink",
            name="average_aftertaste",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="drink",
            name="average_taste",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="review",
            name="country_purchased",
            field=models.CharField(blank=True, null=True),
        ),
    ]
