# Generated by Django 5.0.1 on 2024-07-30 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drink", "0011_rename_country_review_country_purchased_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="drink",
            name="caffeine_per_hundred_ml",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
    ]
