# Generated by Django 5.0.1 on 2024-08-26 18:27

import drink.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drink", "0012_drink_caffeine_per_hundred_ml"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drink",
            name="image",
            field=models.ImageField(
                default="default.png", upload_to=drink.models.drink_file_name
            ),
        ),
    ]
