# Generated by Django 5.0.1 on 2024-11-04 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("drink", "0013_alter_drink_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="drink",
            name="average_aftertaste",
        ),
        migrations.RemoveField(
            model_name="review",
            name="aftertaste",
        ),
    ]
